---
# configure_and_start_salt-minion/tasks/main.yml

- name: "Create /etc/salt/minion.d/master.conf"
  ansible.builtin.copy:
    dest: '/etc/salt/minion.d/master.conf'
    content: "master: {{ salt_master_ip_or_hostname }}\n"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Start salt-minion.service'
