---
# configure_and_start_salt-minion/handlers/main.yml

- name: 'Restart salt-minion.service'
  service:
    name: 'salt-minion.service'
    state: 'restarted'

- name: 'Start salt-minion.service'
  service:
    name: 'salt-minion.service'
    state: 'started'
    enabled: 'true'
